### ISSUE TITLE
Post tidy-up questions/tasks

### ISSUE THREAD

**Issue by danpage** [scarv/xcrypto-spec#25]
After a (protracted) tidy-up of the spec. there are a few things that might be worth thinking about and/or smoothing over.  Maybe it's worth splitting these into multiple issues, but I wanted to at least capture them first.

- `xc.[ld,st]*` all seem to use `b0` but the convention elsewhere is to index the field only if there are more than one: change `b0` to `b`?
- Since we have `xc.[ldr,str].*` there's an argument *immediate* (vs. register) indexed versions could also make sense; on one hand this explodes the number of instructions further, on the other it's orthogonal wrt. other similar choices elsewhere.
- In Class 2.3, the semantics for the permutation instructions need a tidy-up: they use C-style syntax currently!  I've left this for later ...
- ... the naming of the permutation instructions grates a little, in the sense it doesn't follow the same sort of approach as elsewhere: I'd argue we rename along the lines of
  - `pbit` to `perm.1f` (for 1bit, forward)
  - `pbyte` to `perm.8f` (for 8bit, reverse)
  - `ipbit` to `perm.1r` (for 1bit, reverse)
  - `ipbyte` to `perm.8r` (for 8bit, reverse) *if* this makes sense, which it might not,
  - `bmv` to `bmov` (to match use of `mov` elsewhere).
- In Class 2.4, I think it'd be worth rethinking the encoding.  If we swap from encoding n and deriving w to encoding w and deriving n, that means *if* it's attractive to do so, XCLEN can be scaled without changing the instruction semantics: the number of fields, i.e., n, will change per XCLEN but this is captured automatically.
- We have an `xc.init` already; maybe it'd be worth considering an `xc.enter` and `xc.leave` which implement a push and pop of XCrypto state wrt. some GPR (e.g., stack pointer) to reduce context switch overhead?

**Comment by ben-marshall** [comment]
> `xc.[ld,st]*` all seem to use `b0` but the convention elsewhere is to index the field only if there are more than one: change `b0` to `b`?

Agreed. This sort of thing happens because in binutils, it makes life easier to only ever have one name for the same bitfield (as characterised by a position, and size). I think I carried the practice over into the spec. It makes sense to make it jsut `b` in the spec.

> Since we have `xc.[ldr,str].*` there's an argument *immediate* (vs. register) indexed versions could also make sense; on one hand this explodes the number of instructions further, on the other it's orthogonal wrt. other similar choices elsewhere.

I don't know what an immediate indexed version is? One where the immediates are always aligned to the natural data type? If that's the case, I'm not sure how useful they would be. The compiler is already set up to use the normal `register+immediate` variants. An indexed version would only serve to increase the reach of the immediates, which hasn't been a problem so far.

> In Class 2.3, the semantics for the permutation instructions need a tidy-up: they use C-style syntax currently!  I've left this for later ...

Yeah, these instructions are a pig to specify nicely.

> ... the naming of the permutation instructions grates a little
> `pbit` to `perm.1f` (for 1bit, forward)
> `pbyte` to `perm.8f` (for 8bit, reverse)
> `ipbit` to `perm.1r` (for 1bit, reverse)
> `ipbyte` to `perm.8r` (for 8bit, reverse) *if* this makes sense, which it might not,
> `bmv` to `bmov` (to match use of `mov` elsewhere).

I agree with all of these.

> In Class 2.4, I think it'd be worth rethinking the encoding.  If we swap from encoding n and deriving w to encoding w and deriving n, that means *if* it's attractive to do so, XCLEN can be scaled without changing the instruction semantics: the number of fields, i.e., n, will change per XCLEN but this is captured automatically.

I agree that the encoding needs rethinking. It's been on my list for some time and I'd like to do it before trying to re-write any of the reference implementation. There are two sub-points:
1. how to pack the bitfield which contains `n` or `w` into the instructuion. Currently it is spread across three discontiguous bits, which makes encoding the immediate shift variants ugly as hell. This will definietly change.
2. Whether to encode `n` or `w` and derive the other. I think you're right about encoding `w`. I need to look at what it means on the implementation side, but yeah, I think it would be much nicer from a specification point of view.

> We have an `xc.init` already; maybe it'd be worth considering an `xc.enter` and `xc.leave` which implement a push and pop of XCrypto state wrt. some GPR (e.g., stack pointer) to reduce context switch overhead?

Oooerrr..
I'd want to talk to some software people about this. Clearly, RISC-V has a code density problem which instructions like this can help. *However*, I don't know how useful these are to an extension like XCrypto, assuming that they would only work on XCrypto state.
- If they were to work on both GPRs and XCRs, then I think that would be overstepping our goal of an extension which can be implemented in a "minimally invasive" way.
- If they were just to work on XCRs, then I'm not so sure. If we implement `memcpy` (#24 ) then we can't argue there would be much overhead to the LSU in implementing this. However, I haven't yet had to implement an algorithm which *needed* to do stack saves of XCrypto registers from a function call/return perspective.
- I can see it would be useful from a context save/restore point of view. But, I don't think you can make a code density argument there, the number of context-save/restore routines in a system is very small (afaik), so their contribution to (static) code size is tiny. It certainly won't be faster because the bottle neck is the data memory bus. It *would* be more energy efficient (better dynamic code density), and there would be scope for intra-instruction hiding countermeasures, but I'm still not sold yet.

**Comment by ben-marshall** [comment]
Closing as this discussion related to the `v0.15.0` branch and we are now on `v1.0.0`.
